"use client";

import Link from "next/link";
import { FormEvent, useEffect, useRef, useState } from "react";

type Page = "home" | "about" | "expertise" | "projects" | "ventures" | "contact";
const nav: { href: string; label: string; page: Page }[] = [{href:"/",label:"Home",page:"home"},{href:"/about",label:"About",page:"about"},{href:"/expertise",label:"Expertise",page:"expertise"},{href:"/projects",label:"Projects",page:"projects"},{href:"/ventures",label:"Ventures",page:"ventures"},{href:"/contact",label:"Contact",page:"contact"}];
const skills = ["Shopify","React","Next.js","Node.js","Flutter","SaaS","ERP","Meta Ads","Google Ads","TikTok Ads","SEO","Analytics","Automation"];
const expertise = [
  {no:"01",title:"E-Commerce & DTC",desc:"Building commerce experiences from storefront to fulfillment, with a real understanding of technology and operations.",items:["Shopify Development","Liquid","Theme Customization","Product Research","Store Architecture","CRO","COD Operations","Courier Management","RTO Management"]},
  {no:"02",title:"Development & Engineering",desc:"Responsive web products, business software and connected applications built with modern stacks.",items:["React.js","Next.js","Node.js","REST APIs","Frontend","Backend","Flutter","SaaS","ERP","Database Apps"]},
  {no:"03",title:"Performance Marketing",desc:"Connecting creative, advertising, analytics and conversion systems to produce measurable growth.",items:["Meta Ads","TikTok Ads","Google Ads","Tracking","Creative Strategy","Retargeting","ROAS Analysis","Funnels"]},
  {no:"04",title:"Search & Growth",desc:"Finding durable growth through search visibility, testing, measurement and continuous optimization.",items:["Technical SEO","Keyword Research","Content Optimization","Analytics","KPI Monitoring","CRO","Growth Experiments"]},
  {no:"05",title:"Business Operations",desc:"The operating layer that turns a digital storefront into a reliable commercial system.",items:["Product Sourcing","Supplier Coordination","Pricing","Order Management","Logistics","Cash Flow Awareness","CX","Team Coordination"]},
];

function Arrow(){return <span aria-hidden="true">↗</span>}
function Logo(){return <Link href="/" className="logo" aria-label="YASEENX home">YASEEN<span>X</span></Link>}
function Header({page}:{page:Page}){const[open,setOpen]=useState(false);const[scrolled,setScrolled]=useState(false);useEffect(()=>{const f=()=>setScrolled(window.scrollY>30);f();window.addEventListener("scroll",f,{passive:true});return()=>window.removeEventListener("scroll",f)},[]);return <><header className={`nav-wrap ${scrolled?"scrolled":""}`}><Logo/><nav className="desktop-nav" aria-label="Primary navigation">{nav.map(n=><Link key={n.page} className={page===n.page?"active":""} href={n.href}>{n.label}</Link>)}</nav><Link className="nav-cta" href="/contact">Let&apos;s work <Arrow/></Link><button className="menu-button" onClick={()=>setOpen(true)} aria-label="Open menu"><i/><i/></button></header><div className={`mobile-menu ${open?"open":""}`} aria-hidden={!open}><div className="mobile-top"><Logo/><button onClick={()=>setOpen(false)} aria-label="Close menu">×</button></div><nav>{nav.map((n,i)=><Link key={n.page} href={n.href} onClick={()=>setOpen(false)}><small>0{i+1}</small>{n.label}</Link>)}</nav><p>Karachi · Available worldwide</p></div></>}
function DigitalCore({compact=false}:{compact?:boolean}){const ref=useRef<HTMLDivElement>(null);const move=(e:React.PointerEvent)=>{if(!ref.current)return;const r=ref.current.getBoundingClientRect();ref.current.style.setProperty("--rx",`${(e.clientY-r.top-r.height/2)/26}deg`);ref.current.style.setProperty("--ry",`${(e.clientX-r.left-r.width/2)/26}deg`)};const nodes=compact?["COMMERCE","SAAS","GROWTH","CODE"]:["E-COMMERCE","SAAS","DEVELOPMENT","GROWTH","AI","ANALYTICS"];return <div className={`core-scene ${compact?"compact":""}`} ref={ref} onPointerMove={move} onPointerLeave={()=>{ref.current?.style.setProperty("--rx","0deg");ref.current?.style.setProperty("--ry","0deg")}}><div className="core-grid"/><div className="orbit orbit-a"/><div className="orbit orbit-b"/><div className="orbit orbit-c"/><div className="core"><div className="core-inner">YX</div></div>{nodes.map((n,i)=><span className={`node n${i+1}`} key={n}>{n}</span>)}</div>}
function SectionTitle({eyebrow,title,intro}:{eyebrow:string;title:string;intro?:string}){return <div className="section-title reveal"><p className="eyebrow"><span/>{eyebrow}</p><h2>{title}</h2>{intro&&<p className="lead">{intro}</p>}</div>}
function Footer(){return <footer><div><Logo/><p>Digital Architecture. Commerce. Growth.</p></div><div className="footer-links">{nav.map(n=><Link key={n.page} href={n.href}>{n.label}</Link>)}</div><div className="footer-bottom"><span>© 2026 Mohammad Yaseen Aslam</span><span>Karachi, Pakistan · Working globally</span></div></footer>}
function Shell({page,children}:{page:Page;children:React.ReactNode}){useEffect(()=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add("visible")),{threshold:.1});document.querySelectorAll(".reveal").forEach(el=>io.observe(el));return()=>io.disconnect()},[]);return <><div className="noise"/><Header page={page}/><main>{children}</main><Footer/></>}
function ProjectCard({venture,title,role,desc,theme,href,external=false}:{venture:string;title:string;role:string;desc:string;theme:string;href:string;external?:boolean}){return <article className={`project-card ${theme} reveal`}><div className="mockup"><div className="mock-top"><i/><i/><i/></div>{theme==="commerce"?<div className="shop-ui"><b>PRIMEPAKS</b><div/><div/><div/><small>PRODUCTS · ORDERS · GROWTH</small></div>:<div className="dash-ui"><b>NOVASCALE</b><i/><i/><i/><div/><small>WORKFLOW SYSTEM</small></div>}</div><div className="project-meta"><span>{venture}</span><span>{role}</span></div><h3>{title}</h3><p>{desc}</p><Link href={href} target={external?"_blank":undefined} rel={external?"noreferrer":undefined}>View project <Arrow/></Link></article>}
function PageHero({eyebrow,title,intro}:{eyebrow:string;title:React.ReactNode;intro:string}){return <section className="page-hero"><div className="page-hero-copy reveal visible"><p className="eyebrow"><span/>{eyebrow}</p><h1>{title}</h1><p>{intro}</p></div><DigitalCore compact/></section>}

function Home(){return <Shell page="home"><section className="hero"><div className="hero-copy reveal visible"><div className="status"><i/> Available for global opportunities</div><p className="kicker">MOHAMMAD YASEEN ASLAM · DIGITAL ARCHITECT</p><h1>I Build Digital Products, <em>Commerce Brands</em> & Growth Systems.</h1><p className="hero-lead">A full-stack developer, e-commerce entrepreneur and growth marketer creating scalable digital experiences where technology meets business.</p><div className="button-row"><Link className="button primary" href="/projects">Explore my work <Arrow/></Link><Link className="button secondary" href="/contact">Let&apos;s work together</Link></div><div className="founders"><span>Founder of <b>PrimePaks</b></span><span>Creator of <b>NovaScale</b></span></div></div><div className="hero-visual"><DigitalCore/></div><div className="scroll-cue">SCROLL TO EXPLORE <i/></div></section>
<section className="intro section-pad"><SectionTitle eyebrow="WHO I AM" title="More than a developer. I understand the entire digital business ecosystem."/><div className="intro-grid reveal"><p>My work sits at the intersection of technology, e-commerce, marketing and business operations. I don&apos;t only build websites — I understand how products are sourced, presented, marketed, sold, tracked and scaled.</p><p>From Shopify stores and SaaS products to advertising, analytics and commerce operations, I approach every project as one connected business system.</p></div><div className="skill-marquee"><div>{[...skills,...skills].map((s,i)=><span key={`${s}-${i}`}>{s}</span>)}</div></div></section>
<section className="stats section-pad reveal">{[["20+","Shopify & e-commerce stores"],["Full-Cycle","Commerce operations"],["Web + Mobile","Development experience"],["Global","Digital ambition"]].map(s=><div key={s[0]}><strong>{s[0]}</strong><span>{s[1]}</span></div>)}</section>
<section className="expertise-preview section-pad"><SectionTitle eyebrow="CONNECTED CAPABILITIES" title="One skillset. Multiple growth engines." intro="Strategy, engineering and execution — designed as a single system."/><div className="expertise-list">{expertise.slice(0,4).map(x=><article className="expertise-row reveal" key={x.no}><span>{x.no}</span><h3>{x.title}</h3><p>{x.desc}</p><Arrow/></article>)}</div><Link className="text-link" href="/expertise">Explore all expertise <Arrow/></Link></section>
<section className="selected section-pad"><SectionTitle eyebrow="SELECTED WORK" title="Products, platforms & commerce experiences."/><div className="project-grid"><ProjectCard venture="E-Commerce Venture" title="PrimePaks" role="Founder / Owner" theme="commerce" desc="A live commerce venture connecting storefront, acquisition, operations and customer experience." href="https://primepaks.store" external/><ProjectCard venture="Software / SaaS" title="NovaScale" role="Founder / Creator" theme="saas" desc="Business software concepts designed around clarity, automation and scalable workflows." href="/projects"/></div></section>
<section className="quote section-pad reveal"><p>Build with technology.<br/><em>Grow with data.</em><br/>Think like an owner.</p><span>— Mohammad Yaseen Aslam</span></section><section className="final-cta section-pad reveal"><p className="eyebrow"><span/>YOUR NEXT DIGITAL PROJECT</p><h2>Let&apos;s Build What<br/>Comes Next.</h2><p>Have a business, product or ambitious idea? Let&apos;s turn it into a digital experience designed to perform and scale.</p><div className="button-row"><Link className="button primary" href="/contact">Start a conversation <Arrow/></Link><Link className="button secondary" href="/projects">View my work</Link></div></section></Shell>}

function About(){const journey=[["E-Commerce Journey","Worked deeply with online stores, product management and digital commerce systems."],["Marketing Leadership","Led digital marketing and growth activity with an end-to-end commercial view."],["Education & Management","Combined practical commerce operations with teaching as an E-Commerce Instructor & Manager."],["Product Development","Built frontend/backend applications, SaaS systems, ERP concepts and Flutter applications."],["Entrepreneurship","Built and operated independent ventures including PrimePaks and NovaScale."],["Current Mission","Building scalable digital brands, software products and global technology businesses."]];return <Shell page="about"><PageHero eyebrow="ABOUT MOHAMMAD YASEEN" title={<>Commerce mindset.<br/><em>Engineering execution.</em></>} intro="An entrepreneur, developer and digital marketer focused on scalable online businesses and technology-driven products."/><section className="about-copy section-pad"><div className="big-index">01</div><div className="reveal"><p>My experience spans Shopify development, custom web applications, SaaS systems, ERP solutions, Flutter mobile applications and digital advertising.</p><p>Instead of specializing in one isolated part, I work across technology, customer experience, marketing, analytics, conversion, order management and operations.</p></div></section><section className="beliefs section-pad"><article className="glass reveal"><small>MY PHILOSOPHY</small><h2>Technology should create measurable value.</h2><p>It should solve real problems, build clarity and create systems that can scale.</p></article><article className="glass reveal"><small>MY APPROACH</small><h2>Understand. Design. Build. Measure. Improve.</h2><p>Start with the business, engineer the experience, then scale what works.</p></article></section><section className="journey section-pad"><SectionTitle eyebrow="CAREER JOURNEY" title="Built across the full digital stack."/><div className="timeline">{journey.map((j,i)=><article className="reveal" key={j[0]}><span>0{i+1}</span><div><h3>{j[0]}</h3><p>{j[1]}</p></div></article>)}</div></section></Shell>}

function Expertise(){return <Shell page="expertise"><PageHero eyebrow="EXPERTISE" title={<>One skillset.<br/><em>Multiple growth engines.</em></>} intro="Connected capability across commerce, engineering, acquisition, search and operations."/><section className="expertise-full section-pad"><div className="expertise-list">{expertise.map(x=><article className="skill-block reveal" key={x.no}><div className="skill-head"><span>{x.no}</span><h2>{x.title}</h2></div><p>{x.desc}</p><div className="chips">{x.items.map(i=><span key={i}>{i}</span>)}</div></article>)}</div></section><section className="galaxy-section section-pad"><SectionTitle eyebrow="SKILLS GALAXY" title="Disciplines in one orbit." intro="A connected perspective turns specialist capabilities into complete business systems."/><DigitalCore/></section><section className="markets section-pad reveal"><small>ADDITIONAL ANALYTICAL EXPERIENCE</small><h2>Financial Markets</h2><p>I have explored forex trading and financial market analysis, developing experience with market structure, risk awareness, technical analysis and disciplined decision-making. This is analytical exposure, not financial advice.</p></section></Shell>}

function Projects(){const flow=["Research","Product","Creative","Campaign","Landing Page","Conversion","Fulfillment","Retention","Analytics","Optimize"];return <Shell page="projects"><PageHero eyebrow="SELECTED WORK" title={<>Products, platforms &<br/><em>commerce experiences.</em></>} intro="Real ventures and focused experiments where product, technology and growth work together."/><section className="project-showcase section-pad"><ProjectCard venture="E-Commerce Venture" title="PrimePaks" role="Founder / Owner" theme="commerce" desc="Store development, product strategy, advertising, conversion tracking, courier operations, creative direction and growth — managed as one commerce system." href="https://primepaks.store" external/><ProjectCard venture="Software / SaaS Venture" title="NovaScale" role="Founder / Creator" theme="saas" desc="SaaS architecture, dashboards, workflow design, frontend, backend and automation concepts for modern operations." href="/ventures"/></section><section className="other-work section-pad"><SectionTitle eyebrow="DEVELOPMENT EXPERIENCE" title="Built for screens, systems & scale."/><div className="work-cards"><article className="glass reveal"><span>SHOPIFY</span><h3>E-Commerce Store Development</h3><p>Custom sections, product pages, landing pages, mobile optimization and conversion-focused experiences across Dawn, Motion, Prestige, Empire, Impulse, Ella, Kalles and Minimog.</p></article><article className="glass reveal"><span>WEB SYSTEMS</span><h3>Business Systems & Applications</h3><p>ERP concepts, SaaS applications and full-stack systems connecting interface, API, backend and data.</p></article><article className="glass reveal"><span>MOBILE</span><h3>Mobile Commerce</h3><p>Flutter-based commerce apps and web-to-mobile concepts including push notifications and customer engagement.</p></article></div></section><section className="funnel section-pad"><SectionTitle eyebrow="MARKETING SYSTEM" title="From click to customer." intro="Marketing connects to product, pricing, experience, fulfillment and customer satisfaction."/><div className="flow">{flow.map((f,i)=><div className="reveal" key={f}><span>{String(i+1).padStart(2,"0")}</span><b>{f}</b></div>)}</div></section></Shell>}

function Ventures(){const reasons=[["Business + Technology","I understand both the commercial objective and the technology required to execute it."],["E-Commerce Experience","The full customer journey — from impression to delivered order."],["Development Capability","Concepts become responsive and functional digital products."],["Performance Mindset","Data, KPIs and conversion metrics guide decisions."],["Connected Execution","Development, marketing and operations inform one another."],["Founder Mentality","Ownership, speed and long-term scalability shape the work."]];return <Shell page="ventures"><PageHero eyebrow="VENTURES" title={<>Building beyond<br/><em>client work.</em></>} intro="The strongest understanding of business comes from operating real products and connecting technology, marketing and operations."/><section className="ecosystem section-pad"><div className="ecosystem-core reveal"><b>YASEENX</b><span>VENTURE ECOSYSTEM</span></div>{[["COMMERCE","PrimePaks"],["TECHNOLOGY","NovaScale"],["SERVICES","Digital Projects"],["GROWTH","Marketing Systems"]].map((x,i)=><article className={`eco e${i+1} reveal`} key={x[0]}><small>{x[0]}</small><h3>{x[1]}</h3></article>)}</section><section className="founder-story section-pad"><SectionTitle eyebrow="FOUNDER MINDSET" title="When you operate the business, everything connects." intro="Technology, marketing, customer experience and operations stop being separate departments — they become parts of one system."/><div className="venture-pair"><article className="glass reveal"><span>01 · E-COMMERCE</span><h2>PrimePaks</h2><p>Founder / Owner</p><Link href="https://primepaks.store" target="_blank">Visit venture <Arrow/></Link></article><article className="glass reveal"><span>02 · SOFTWARE / SAAS</span><h2>NovaScale</h2><p>Founder / Creator</p><Link href="/projects">Explore direction <Arrow/></Link></article></div></section><section className="why section-pad"><SectionTitle eyebrow="WHY WORK WITH ME" title="I don't see a website. I see the business behind it."/><div className="reason-grid">{reasons.map((r,i)=><article className="reveal" key={r[0]}><span>0{i+1}</span><h3>{r[0]}</h3><p>{r[1]}</p></article>)}</div></section><section className="process section-pad"><SectionTitle eyebrow="PROCESS" title="From ambition to operating system."/><div className="process-track">{[["DISCOVER","Understand"],["STRATEGIZE","Define"],["DESIGN","Experience"],["BUILD","Develop"],["LAUNCH","Deploy"],["GROW","Improve"]].map((p,i)=><article className="reveal" key={p[0]}><span>0{i+1}</span><h3>{p[0]}</h3><p>{p[1]}</p></article>)}</div></section></Shell>}

function Contact(){const[status,setStatus]=useState("");const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setStatus("Sending…");const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));try{const res=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});if(!res.ok)throw new Error();setStatus("Message received. I’ll be in touch soon.");form.reset()}catch{setStatus("Please email me directly — I’d still love to hear from you.")}};return <Shell page="contact"><section className="contact-hero"><div className="reveal visible"><p className="eyebrow"><span/>START A CONVERSATION</p><h1>Let&apos;s build something<br/><em>that matters.</em></h1><p>Whether you&apos;re building an e-commerce brand, digital platform, SaaS product or growth system — tell me where you want to go.</p><div className="contact-direct"><a href="mailto:mohammadyaseenaslam302@gmail.com"><small>EMAIL</small>mohammadyaseenaslam302@gmail.com <Arrow/></a><a href="tel:+923009226943"><small>PHONE</small>+92 300 922 6943 <Arrow/></a><a href="https://www.linkedin.com/in/mohammad-yaseen-86942a2b5" target="_blank" rel="noreferrer"><small>LINKEDIN</small>Connect professionally <Arrow/></a></div></div><form className="contact-form glass reveal visible" onSubmit={submit}><div className="form-intro"><span>PROJECT BRIEF</span><b>Usually replies within 24–48 hours</b></div><label>Your name<input required name="name" autoComplete="name" placeholder="Your name"/></label><label>Email address<input required type="email" name="email" autoComplete="email" placeholder="you@company.com"/></label><label>What are you building?<select required name="project"><option value="">Select project type</option><option>E-Commerce</option><option>Website / Web App</option><option>SaaS / Business System</option><option>Growth & Marketing</option><option>Other</option></select></label><label>Tell me about the opportunity<textarea required minLength={20} name="message" rows={5} placeholder="The challenge, goal and what success looks like…"/></label><input className="honey" name="company_website" tabIndex={-1} autoComplete="off"/><button className="button primary" type="submit">Send project brief <Arrow/></button><p className="form-status" aria-live="polite">{status}</p></form></section></Shell>}
export default function YaseenSite({page}:{page:Page}){if(page==="about")return <About/>;if(page==="expertise")return <Expertise/>;if(page==="projects")return <Projects/>;if(page==="ventures")return <Ventures/>;if(page==="contact")return <Contact/>;return <Home/>}
